// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using medic_api.DAL;

namespace medic_api.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("medic_api.DAL.Models.MedicalData", b =>
                {
                    b.Property<Guid>("MedicalDataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("uuid");

                    b.Property<int>("Age")
                        .HasColumnName("age")
                        .HasColumnType("integer");

                    b.Property<int>("BloodPressure")
                        .HasColumnName("bloodpressure")
                        .HasColumnType("integer");

                    b.Property<double>("Bmi")
                        .HasColumnName("bmi")
                        .HasColumnType("double precision");

                    b.Property<double>("DiabetesPedigreeFunction")
                        .HasColumnName("diabetespedigreefunction")
                        .HasColumnType("double precision");

                    b.Property<int>("Glucose")
                        .HasColumnName("glucose")
                        .HasColumnType("integer");

                    b.Property<int>("Insulin")
                        .HasColumnName("insulin")
                        .HasColumnType("integer");

                    b.Property<bool?>("Prediction")
                        .HasColumnName("prediction")
                        .HasColumnType("boolean");

                    b.Property<int>("Pregnancies")
                        .HasColumnName("pregnancies")
                        .HasColumnType("integer");

                    b.Property<bool?>("Result")
                        .HasColumnName("result")
                        .HasColumnType("boolean");

                    b.Property<int>("SkinThickness")
                        .HasColumnName("skinthickness")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnName("userid")
                        .HasColumnType("uuid");

                    b.HasKey("MedicalDataId");

                    b.HasIndex("UserId");

                    b.ToTable("medicaldata");
                });

            modelBuilder.Entity("medic_api.DAL.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("uuid");

                    b.Property<string>("FirstName")
                        .HasColumnName("firstname")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnName("lastname")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnName("password")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .HasColumnName("role")
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .HasColumnName("username")
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("users");
                });

            modelBuilder.Entity("medic_api.DAL.Models.MedicalData", b =>
                {
                    b.HasOne("medic_api.DAL.Models.User", "User")
                        .WithMany("MedicalDataset")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
